import asyncio
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import httpx
import uuid

# Add backend dir to path so we can import modules
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from github_app import get_installation_token
from github_api import fetch_installation_repos, fetch_repo_issues
from agent_manager import run_agent_job
from motor.motor_asyncio import AsyncIOMotorClient

async def create_test_issue(owner: str, repo: str, token: str, title: str, body: str):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    data = {"title": title, "body": body}
    async with httpx.AsyncClient() as client:
        res = await client.post(url, headers=headers, json=data)
        res.raise_for_status()
        return res.json()

async def close_issue(owner: str, repo: str, issue_number: int, token: str):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    data = {"state": "closed"}
    async with httpx.AsyncClient() as client:
        res = await client.patch(url, headers=headers, json=data)
        res.raise_for_status()
        return res.json()

async def main():
    print("--- Starting Agent Integration Test ---")
    load_dotenv(Path(__file__).parent.parent / '.env')
    
    # Connect to local DB for agent_manager
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    client = AsyncIOMotorClient(mongo_url)
    db = client.codetok
    
    installation_id = os.environ.get("GITHUB_APP_INSTALLATION_ID")
    if not installation_id:
        print("❌ Error: GITHUB_APP_INSTALLATION_ID not set")
        return
        
    print("Fetching GitHub App Token...")
    token_data = await get_installation_token(installation_id)
    token = token_data['token']
    
    print("Fetching installed repositories...")
    repos = await fetch_installation_repos(token)
    if not repos:
        print("❌ Error: GitHub App has no repositories installed.")
        return
        
    target_repo = repos[0]
    owner = target_repo['owner']['login']
    repo_name = target_repo['name']
    full_repo = f"{owner}/{repo_name}"
    print(f"✅ Selected target repository: {full_repo}")
    
    # 1. Create a Test Issue
    test_title = f"[Test] Integrate real background agent e2e {uuid.uuid4().hex[:6]}"
    test_body = "This is a test issue generated by the CodeTok integration test. Please fix the dummy file by adding a console log."
    
    print(f"\n1. Creating test issue: '{test_title}'...")
    created_issue = await create_test_issue(owner, repo_name, token, test_title, test_body)
    issue_number = created_issue['number']
    issue_id = f"gh_issue_{owner}_{repo_name}_{issue_number}"
    print(f"✅ Issue created. Issue Number: #{issue_number}, Internal ID: {issue_id}")
    
    # Save the issue to the mock database so agent_manager can fetch its title/description for the prompt
    await db.issues.insert_one({
        "issue_id": issue_id,
        "title": test_title,
        "description": test_body,
        "project": full_repo
    })
    
    # 2. Verify Issue is fetched by our API endpoint equivalent
    print("\n2. Waiting 3 seconds for GitHub replication, then fetching repository issues...")
    await asyncio.sleep(3)
    fetched_issues = await fetch_repo_issues(owner, repo_name, token, filter_bot=False)
    found = any(i['number'] == issue_number for i in fetched_issues)
    if found:
        print("✅ Issue successfully verified in fetch_repo_issues.")
    else:
        print("❌ Failed to fetch the newly created issue.")
        # We can clean up here if needed
        await close_issue(owner, repo_name, issue_number, token)
        return
        
    # 3. Spawn the Agent background job
    job_id = f"test_job_{uuid.uuid4().hex[:8]}"
    print(f"\n3. Submitting Agent Job via Run Agent Function (Job ID: {job_id})...")
    
    # Insert dummy job doc first
    from datetime import datetime, timezone
    await db.agent_jobs.insert_one({
        "job_id": job_id,
        "issue_id": issue_id,
        "agent_type": "codex",  # or opencode
        "repo": full_repo,
        "status": "Pending",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "traces": [],
        "summary": None
    })
    
    try:
        # Run agent job synchronously for this test
        # Note: Depending on your local setup, 'codex' or 'opencode' must be in your PATH
        await run_agent_job(db, job_id, issue_id, "codex", full_repo)
    except Exception as e:
        print(f"⚠️ Agent run exception: {e}")
        
    print("\n4. Checking Agent Job Status in Database...")
    job = await db.agent_jobs.find_one({"job_id": job_id})
    print(f"Final Status: {job.get('status')}")
    print("Traces generated:")
    for trace in job.get('traces', []):
        print(f"  - {trace.get('step')}")
        
    # 5. Cleanup
    print(f"\n5. Cleaning up test issue #{issue_number}...")
    await close_issue(owner, repo_name, issue_number, token)
    print("✅ Issue closed.")
    
    print("\n🎉 Test script finished. The PR created by the agent should remain open for manual UI verification.")

if __name__ == "__main__":
    asyncio.run(main())
